version: '3.8'

services:
  pokedex:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - components
      - utils

  components:
    build:
      context: .
      dockerfile: Dockerfile
    command: echo "Components package built successfully"

  utils:
    build:
      context: .
      dockerfile: Dockerfile
    command: echo "Utils package built successfully"